### ISSUE TITLE
Agregar postgres-client en el docker del SIU

### ISSUE THREAD

**Issue by asabolansky** [SIU-Toba/docker-guarani#1]
Hola, 
en el docker de la app web, faltaría postgresql-client porque no se pueden correr comandos de migración de base ni nada, que necesitan el comando psql.

Saludos
Alejandro

**Comment by andres-blanco** [comment]
Hola Ale, ahí se agregó el paquete a docker-web:latest.
Se están rebuildeando las imágenes en [docker-hub](https://hub.docker.com/r/siutoba/docker-web/builds/). Cuando terminen ya vas a tener disponible psql.

Gracias!
